name = "mailfree"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"
keep_vars=true

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free_db" #你的d1数据库名称
database_id = "d1b7d84e-5eea-4b46-af09-36e874b74dac" # 你的database_id
# 登录会话过期时间（单位：天，默认7天）
# 环境变量
[vars]
# FORWARD_RULES="[{"prefix":"vip","email":"a@example.com"},{"prefix":"*","email":"example@qq.com"}]"
ADMIN_NAME="zhangsan"
ADMIN_PASSWORD="Fanqiang9."
GUEST_PASSWORD="Fanqiang9."
JWT_TOKEN="fjiwaiv23164s4fdsfs6df6wfdy"
JWT_TOKENGUEST_PASSWORD="Fanqiang9."
SESSION_EXPIRE_DAYS="365"
MAIL_DOMAIN="113.qzz.io"
RESEND_API_KEY="Fanqiang9."



# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"


# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true